apiVersion: v1
kind: Pod
metadata:
  name: bidding-auction-pod
  namespace: bidding-system
spec:
  containers:
    - image: felipeogutierrez/bidding-system:0.1
      name: bidding-auction-system
      imagePullPolicy: Always # Always|IfNotPresent
      args: [ "--bidders", "http://bidder-01-0.bidder-01-service.bidding-system.svc.cluster.local:8081,http://bidder-02-0.bidder-02-service.bidding-system.svc.cluster.local:8082,http://bidder-03-0.bidder-03-service.bidding-system.svc.cluster.local:8083" ]
      ports:
        - name: http
          containerPort: 8080
        - name: bidder-01
          containerPort: 8081
        - name: bidder-02
          containerPort: 8082
        - name: bidder-03
          containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: bidding-auction-service
  namespace: bidding-system
spec:
  type: ClusterIP
  ports:
    - name: bidding-auction-service
      protocol: TCP
      port: 8080
      targetPort: 8080
